#!/bin/sh

# to copy RSA key use: ssh-copy-id $USER@$IP

IP=185.86.77.209
PROJECT_NAME=demo
ROOT=/www/$PROJECT_NAME
LOGS=/www/logs
USER=root

# clean and create directories
ssh $USER@$IP rm -rf $ROOT
ssh $USER@$IP mkdir $ROOT
ssh $USER@$IP mkdir -p $LOGS

# update and install required software
ssh $USER@$IP apt-get update
ssh $USER@$IP apt-get install -y python3 python3-dev python3-pip virtualenv nginx supervisor

# copy project files to the server
zip ./build.zip -r ./ -x "*.git*" -x "*venv*" -x "*.idea*"
scp ./build.zip $USER@$IP:$ROOT/
ssh $USER@$IP "unzip -o $ROOT/build.zip -d $ROOT/"
ssh $USER@$IP "rm $ROOT/build.zip"
rm build.zip

# setup python environment
ssh $USER@$IP "virtualenv --no-site-packages -p /usr/bin/python3 $ROOT/venv"
ssh $USER@$IP "source $ROOT/venv/bin/activate && pip install -r $ROOT/requirements.txt"

# copy nginx config
ssh $USER@$IP rm /etc/nginx/sites-enabled/default
scp ./conf/nginx.conf $USER@$IP:/etc/nginx/sites-available/$PROJECT_NAME
ssh $USER@$IP ln -sf /etc/nginx/sites-available/$PROJECT_NAME /etc/nginx/sites-enabled/$PROJECT_NAME

# restart nginx
ssh $USER@$IP /etc/init.d/nginx restart

# copy supervisor config
scp ./conf/supervisor.conf $USER@$IP:/etc/supervisor/conf.d/$PROJECT_NAME.conf

# restart supervisor
ssh $USER@$IP "supervisorctl reread"
ssh $USER@$IP "supervisorctl update"
ssh $USER@$IP "supervisorctl restart $PROJECT_NAME"
